### ISSUE TITLE
Transcriber Unable To Transcribe from a Downloaded Youtube URL

### ISSUE THREAD

**Issue by bytrangle** [AssemblyAI/cookbook#81]
I followed this [guide](https://github.com/AssemblyAI/cookbook/blob/master/core-transcription/transcribe_youtube_videos.ipynb) for using `yt-dlp` to extract a publicly accessible url from a Youtube video, then transcribe it.
When calling `transcriber.transcribe()` on this url, then access the `text` property, I got `None`.

Steps to reproduce it:
1. Install `yt-dlp`
2. Run the following script:

```
import yt_dlp
import assemblyai as aai

URL = 'https://www.youtube.com/watch?v=wtolixa9XTg'

with yt_dlp.YoutubeDL() as ydl:
    info = ydl.extract_info(URL, download=False)

for format in info["formats"][::-1]:
  if format["resolution"] == "audio only" and format["ext"] == "m4a":
    url = format["url"]
    break

print(url)

aai.settings.api_key = "3126406c5a83450b8cdd5b5eb19845b0"
transcriber = aai.Transcriber()
transcript = transcriber.transcribe(url)
print(transcript.text)
```
You should get `None` in the output for `transcript.text`.

![Screenshot from 2024-11-25 05-47-45](https://github.com/user-attachments/assets/2157942d-9e20-4493-82c5-cc7ce1527abf)

The same thing happens when I use AssemblyAI's Javascript SDK, but the message was more detailed:

> Download error, unable to download ... Please make sure the file exists and is accessible from the internet.

But the url passed to Transcriber is indeed publicly accessible.

Given that the guide was last updated a year ago, was there a change in Transcriber that makes it unable to read a publicly available file on `googlevideo.com` domain?

**Comment by m-ods** [comment]
Hey @bytrangle - we don't recommend this approach of transcribing YouTube videos as these URLs are throttled.

**Comment by m-ods** [comment]
I'll work on removing this section of the guide!

**Comment by bytrangle** [comment]
Hello @m-ods . Thanks for getting back. Consider that the guide to transcribing Youtube videos is the most popular article from the Cookbooks page, will you include a different approach to transcribing or remove the guide altogether?

**Comment by m-ods** [comment]
Hey @bytrangle - you can still use options 1 and 2 if you'd like! I've gone ahead and put in a PR to remove option 3
